### ISSUE TITLE
"New window" doesn't work for sli files

### ISSUE THREAD

**Issue by kees-jan** [SCROOM-plugin-cpp/SCROOM-plugin-cpp#10]
**Testcase**
 * Open an 'sli' file
 * Choose File->New Window

**Expected result**
A new window appears showing the same sli file

**Actual result**
Scroom crashes

**Comment by ethoxx** [comment]
I was unfortunately unable to reproduce this issue. However, indeed there were some strange things going on when opening a new window for an SLI file, these are fixed in #12 
It would be great if you could verify that this PR also fixes the issue you experienced.

**Comment by JoostvanPinxten** [comment]
I have not found any issues after the integration of PR #12. I will close this one. If other issues pop up, we can reopen, or make a new issue.

**Comment by kees-jan** [comment]
I, too, cannot reproduce it any more with the latest version.
